### ISSUE TITLE
Add Sheet Parameter

### ISSUE THREAD

**Issue by lrljoe** [Knackline/laravel-excel-to-x#17]
Suggest that you add an option, allowing the user to define which sheet(s) are parsed, in the event of large spreadsheets where they only want to retrieve a single sheet from the spreadsheet.

**Comment by rjsamra** [comment]
We should not do that
Anyways the user can call the $excel->sheet for retrieval of the data from particular sheet

**Comment by rjsamra** [comment]
I am closing this Issue, because this will not be taken up
