### ISSUE TITLE
Suggest removing composer.lock from your repo

### ISSUE THREAD

**Issue by lrljoe** [Knackline/laravel-excel-to-x#18]
This shouldn't be included in a package typically

**Comment by rjsamra** [comment]
Surely, will also remove .gitignore

**Comment by lrljoe** [comment]
Keep .gitignore as it is useful

Just delete the composer.lock from the repo, then add it to .gitignore

Then add a new file:

.gitattributes

Add to that anything that you don't want users to receive when they install the package in the following way, for example:
```
/Readme.md                                       export-ignore
/tests                                           export-ignore
```

So that users won't get the "test" folder or Readme.md file when they "composer require" the package, but it will be in the repository still.

**Comment by rjsamra** [comment]
I have updated the changes requested @lrljoe
